name: Bump

on:
  schedule:
    - cron: 0 13 * * *    
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: couchdb:2.3.0
        ports:
        - 5984:5984
    steps:
    - uses: actions/checkout@v1
    - name: Install Deno
      run: |
        DENO_VERSION=$(cat .denov)
        curl -fsSL https://deno.land/x/install/install.sh | bash -s -- ${DENO_VERSION}
    - name: Check And Bump
      env:
        GITHUB_USER: keroxp
        GITHUB_REPO: deno-couchdb
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        export PATH=$HOME/.deno/bin:$PATH
        sleep 10
        deno run -A https://denopkg.com/keroxp/dink-bot@v0.2.0/main.ts
